### ISSUE TITLE
after `pip install moya` command `moya init` errors out

### ISSUE THREAD

**Issue by bronsen** [moyaproject/moya-techblog#1]
I pip installed moya, then ran `moya init`. This is the error message I get:

```
Initializing site...
Moya project directory not found, run this command from a project directory or specify --location
```

According to `moya init --help` the option `location` should point to the location of the "Moya server code".

Should I have cloned moya instead of pip installing it: pip install does not give me a `site` directory that is mentioned in the readme...

**Comment by willmcgugan** [comment]
Hi,

Moya is an app which runs a Moya project. If you clone the Moya Techblog repos then `cd site`, and run `moya init` from there it, will initialize the blog.

I'll update the readme to clarify...

Will
